h

# Análisis del método `query()` de Pandas para seleccionar datos

En este notebook, analizaremos el método `query()` de Pandas, una de las formas más eficientes y legibles para seleccionar datos de un DataFrame.

Pandas proporciona múltiples métodos para filtrar y seleccionar información; `query()` es uno de los más versátiles, permitiendo realizar consultas complejas de manera sencilla utilizando expresiones similares a SQL.

## ¿Cómo funciona el método `query()`?

El método `query()` recibe como argumento una cadena de texto con la condición que se utilizará para seleccionar las filas del DataFrame.

**Sintaxis básica:**
```python
DataFrame.query('CONDICIÓN_DE_SELECCIÓN')
```

La condición que se expresa en el método `query()` es muy similar a la que se usaría después de la cláusula `WHERE` en una sentencia SQL.

> Por ejemplo:
> ```python
> df.query('columna > 5 and columna2 == "valor"')
> ```

Esto permite escribir filtros complejos de manera más intuitiva y legible, facilitando el análisis y manipulación de los datos.

In [2]:
import pandas as pd

movies = pd.read_csv('../../data/TMDB_movie_dataset_v11.csv')

movies.query('vote_average == 8.364')

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
47336,813454,L'Enfant Terrible,8.364,22,Released,2019-10-20,0,126,False,/8z2JE9Axk7x7GiUJ99WdkaJbVEH.jpg,...,L'Enfant Terrible,"Kobe, a young famous and successful writer, he...",1.886,/x3BZujzWUFUxmUtF70HxpVjAWtm.jpg,NaN,Drama,NaN,Spain,Spanish,love
70448,570034,Christmas Who?,8.364,11,Released,2000-12-06,0,23,False,/h9XbCVzIac1CKvopHLGvYjfauav.jpg,...,Christmas Who?,When Spongebob first learns of Christmas and S...,1.720,/aQBWiIAEDtJDIIhsMsp6qJdyqQZ.jpg,Nobody in Bikini Bottom has ever heard of Chri...,"Animation, Comedy, Family",Nickelodeon Animation Studio,United States of America,English,christmas special
71446,888491,Juice WRLD: Into the Abyss,8.364,11,Released,2021-11-12,0,110,False,/jsbaTgqc5mnYcZzDGpO5MwClTMT.jpg,...,Juice WRLD: Into the Abyss,An intimate and often eye-opening exploration ...,4.173,/8Gc9KX8NxV9YcAjaOhWXGTzhDDf.jpg,NaN,"Documentary, Music","HBO Documentary Films, Confluential Films, The...",United States of America,English,"rapper, music documentary"